### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [ItDev-Angel/kinozal#1]
1)
Переход не работает, страницы нет.
Задание не выполнено.
![image](https://user-images.githubusercontent.com/8464662/173176024-75ed53fe-65d8-438f-8b74-f81e871f8865.png)

2)

В файлах установлены разные отступы.
Т.е. в каком-то файле установлены отступы в 2 пробела, в другом файле отступы составляют 4 пробела.
Допускается отступы или 2, или 4, количество отступов должно быть одинаковым для всех файлов проекта, включая HTML, CSS, JS, TS.
Использование символа табуляции, 1 / 3 / 5 / 7 пробелов в качестве отступов - запрещено.
Определитесь с количеством отступов и настройте их число для каждого файла отдельно, а также исправьте количество пробелов для новых файлов по умолчанию.
Как это сделать - описано в документации используемого вами редактора (вопрос гуглится).
После настройки отступов выполните автоматическое форматирование для всех файлов проекта.

![image](https://user-images.githubusercontent.com/8464662/173176062-6f8693ff-e8ae-4c3b-8f07-fbe49ff464f2.png)

**Comment by Alecto** [comment]
3)
В HTML5 нет такого синтаксиса, вы используете синтаксис XHTML, что противоречит инструкции DOCTYPE html.
Разберитесь в причине появление такого синтаксиса. Обычно виновником является плагин PRETTIER, неправильно установленный в качестве форматтера по умолчанию для HTML-страниц. 
С деталями вы можете ознакомиться в уроке по настройке VSCode.
Затем приведите разметку всех без исключения файлов вашего проекта к стандарту HTML5, удалив обратные слеши для всех непарных тегов.
После этого выполните автоформатирование кода для всех исправленных файлов.

![image](https://user-images.githubusercontent.com/8464662/174873199-bef385ff-0f97-469a-be4f-4812a758c856.png)

4)
форматирование кода в разных файлах разное

**Comment by ItDev-Angel** [comment]
https://github.com/ItDev-Angel/kinozal
https://itdev-angel.github.io/kinozal/page.html

вт, 21 июн. 2022 г. в 21:36, Andrey ***@***.***>:

**Comment by Alecto** [comment]
Теперь отлично, больше ошибок и замечаний нет.
Работа принята.

пн, 27 черв. 2022 р. о 20:12 ItDev-Angel ***@***.***> пише:
